CREATE SEQUENCE SQ_FUNCIONARIO
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SQ_TELEFONE
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SQ_DISTRIBUIDOR
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SQ_TECNOLOGIA_LICENCIADA
START WITH 1
INCREMENT BY 1;

CREATE TABLE FUNCIONARIO(
	ID INT,
    CPF VARCHAR(15) NOT NULL UNIQUE,
    Nome VARCHAR(50),
    Salario NUMBER,
    DataNasc DATE,
    DescricaoEnd VARCHAR(255),
    CepEnd VARCHAR(50),
	ID_Chefe INT,
    CONSTRAINT PK_FUNCIONARIO PRIMARY KEY(ID),
    CONSTRAINT FK_FUNCIONARIO_Chefe FOREIGN KEY (ID_CHEFE) REFERENCES FUNCIONARIO (ID)
);


CREATE TABLE TELEFONE(
    ID_FUNCIONARIO INT,
    ID_TELEFONE INT,
    Telefone VARCHAR(20),
    CONSTRAINT PK_TELEFONE PRIMARY KEY(ID_FUNCIONARIO,ID_TELEFONE),
    CONSTRAINT FK_TELEFONE_ID_FUNCIONARIO FOREIGN KEY(ID_FUNCIONARIO) REFERENCES FUNCIONARIO(ID)

);

CREATE TABLE DEPARTAMENTO(
	Codigo INT,
	Nome VARCHAR(50),
	Descricao VARCHAR(255),
	ID INT NOT NULL UNIQUE,
	CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY(Codigo),
	CONSTRAINT FK_DEPARTAMENTO_ID FOREIGN KEY(ID) REFERENCES FUNCIONARIO(ID)

);

CREATE TABLE DISTRIBUIDOR(
    ID INT,
    CNPJ VARCHAR(20) NOT NULL UNIQUE,
    Nome VARCHAR(50),
    Email VARCHAR(100),
    CONSTRAINT PK_DISTRIBUIDOR PRIMARY KEY (ID)
);

CREATE TABLE TECNOLOGIA_LICENCIADA(
    ID INT,
    Marca_Registrada VARCHAR(50) NOT NULL UNIQUE,
    Descricao VARCHAR(250),
    Cedente VARCHAR(50),
    CONSTRAINT PK_TECNOLOGIA_LICENCIADA PRIMARY KEY (ID)
);

CREATE TABLE PROJETO(
	Cod INT,
	Nome VARCHAR(50),
	Custo NUMBER,
	Status VARCHAR(50),
	DataInicio Date,
	Prazo Date,
	ID INT  NOT NULL,
	CONSTRAINT PK_PROJETO PRIMARY KEY(Cod),
	CONSTRAINT FK_PROJETO_ID FOREIGN KEY(ID) REFERENCES FUNCIONARIO(ID)

);

CREATE TABLE PC(
	Cod INT,
	Classificacao VARCHAR(15),
	Categoria VARCHAR(15),
	CONSTRAINT PK_PC PRIMARY KEY(Cod),
	CONSTRAINT FK_PC_COD_PROJETO FOREIGN KEY(Cod) REFERENCES PROJETO(Cod)

);

CREATE TABLE MOBILE(
	Cod INT,
	Plataforma VARCHAR(15),
	CONSTRAINT PK_MOBILE PRIMARY KEY(Cod),
	CONSTRAINT FK_MOBILE_COD_PROJETO FOREIGN KEY (Cod) REFERENCES PROJETO(Cod)

);


CREATE TABLE TAREFA(
	ID INT,
	Cod INT,
	Descricao VARCHAR(100),
	CONSTRAINT PK_TAREFA PRIMARY KEY (ID,Cod),
	CONSTRAINT FK_TAREFA_COD FOREIGN KEY(Cod) REFERENCES PROJETO(Cod)

);

CREATE TABLE EXECUTA(
	ID_TAREFA INT,
	Cod_PROJETO INT,
	ID_FUNCIONARIO INT,
	CONSTRAINT PK_EXECUTA PRIMARY KEY(ID_TAREFA,Cod_PROJETO,ID_FUNCIONARIO),
	CONSTRAINT FK_EXECUTA_ID_TAREFA FOREIGN KEY(ID_TAREFA,Cod_PROJETO) REFERENCES TAREFA(ID,Cod),
	CONSTRAINT FK_EXECUTA_ID_FUNCIONARIO FOREIGN KEY(ID_FUNCIONARIO) REFERENCES FUNCIONARIO(ID)

);

CREATE TABLE TRABALHA(
	ID INT,
	Codigo INT,
	DataAdmin DATE,
	CONSTRAINT PK_TRABALHA PRIMARY KEY(ID,Codigo,DataAdmin),
	CONSTRAINT FK_TRABALHA_ID FOREIGN KEY(ID) REFERENCES FUNCIONARIO(ID),
	CONSTRAINT FK_TRABALHA_CODIGO  FOREIGN KEY(Codigo) REFERENCES DEPARTAMENTO(Codigo)

);

CREATE TABLE NEGOCIA(
	Cod_PROJETO INT,
	ID_DISTRIBUIDOR INT,
	Data DATE,
	ID_FUNCIONARIO INT NOT NULL,
	CONSTRAINT PK_NEGOCIA PRIMARY KEY(Cod_PROJETO,ID_DISTRIBUIDOR,Data),
	CONSTRAINT FK_NEGOCIA_COD FOREIGN KEY(Cod_PROJETO) REFERENCES PROJETO(Cod),
	CONSTRAINT FK_NEGOCIA_CODIGO FOREIGN KEY(ID_DISTRIBUIDOR) REFERENCES DISTRIBUIDOR(ID),
	CONSTRAINT FK_NEGOCIA_ID FOREIGN KEY(ID_FUNCIONARIO) REFERENCES FUNCIONARIO(ID)
);


CREATE TABLE USA(
	ID_TECNOLOGIA_LICENCIADA INT,
	ID_TAREFA INT,
	Cod_PROJETO INT,
	ID_FUNCIONARIO INT,
	CONSTRAINT PK_USA PRIMARY KEY (ID_TECNOLOGIA_LICENCIADA,ID_TAREFA,Cod_PROJETO,ID_FUNCIONARIO),
	CONSTRAINT FK_USA_ID_TECNOLOGIA_LICENCIADA FOREIGN KEY(ID_TECNOLOGIA_LICENCIADA) REFERENCES TECNOLOGIA_LICENCIADA(ID),
	CONSTRAINT FK_USA_ID_TAREFA_Cod_PROJETO_ID_FUNCIONARIO FOREIGN KEY(ID_TAREFA,Cod_PROJETO,ID_FUNCIONARIO) REFERENCES EXECUTA(ID_TAREFA,Cod_PROJETO,ID_FUNCIONARIO)

);

